cargo-features = [ ]

[workspace]
resolver = "2"
members = [
    "cli",
    "lib",
    "lib/testutils",
    "lib/gen-protos"
]

[workspace.dependencies]
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
backoff = "0.4.0"
blake2 = "0.10.6"
byteorder = "1.4.3"
bytes = "1.4.0"
cargo_metadata = "0.15.4"
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
clap = { version = "4.3.11", features = ["derive", "deprecated"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.10"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
criterion = "0.5.1"
crossterm = { version = "0.26", default-features = false }
digest = "0.10.7"
dirs = "5.0.1"
esl01-renderdag = "0.3.0"
git2 = "0.17.2"
glob = "0.3.1"
hex = "0.4.3"
indexmap = "2.0.0"
insta = { version = "1.30.0", features = ["filters"] }
itertools = "0.11.0"
libc = { version = "0.2.147" }
maplit = "1.0.2"
num_cpus = "1.16.0"
once_cell = "1.18.0"
pest = "2.7.0"
pest_derive = "2.7.0"
prost = "0.11.9"
prost-build = "0.11.9"
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.9.1"
rpassword = "7.2.0"
rustix = { version = "0.38.3", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.100"
slab = "0.4.8"
smallvec = { version = "1.11.0", features = [
    "const_generics",
    "const_new",
    "union",
] }
strsim = "0.10.0"
tempfile = "3.6.0"
test-case = "3.1.0"
textwrap = "0.16.0"
thiserror = "1.0.43"
timeago = { version = "0.4.1", default-features = false }
tokio = "1.29.1"
toml_edit = { version = "0.19.12", features = ["serde"] }
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["std", "ansi", "env-filter", "fmt"] }
version_check = "0.9.4"
watchman_client = "0.8.0"
whoami = "1.4.1"
zstd = "0.12.3"

# put all inter-workspace libraries, i.e. those that use 'path = ...' here in
# their own (alphabetically sorted) block
jj-lib = { path = "lib", version = "=0.7.0", default-features = false }
testutils = { path = "lib/testutils" }

# profile overrides below

[profile.release]
strip = "debuginfo"
codegen-units = 1 
