[package]
name = "jj-cli"
version = "0.8.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.71"  # Remember to update CI, and contributing.md
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jj-cli"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[workspace]
members = ["lib", "lib/testutils", "lib/gen-protos"]

[build-dependencies]
cargo_metadata = "0.15.4"

[dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
clap = { version = "4.3.13", features = ["derive", "deprecated"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.10"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
criterion = {version = "0.5.1", optional = true }
crossterm = { version = "0.26", default-features = false }
dirs = "5.0.1"
esl01-renderdag = "0.3.0"
git2 = "0.17.2"
glob = "0.3.1"
hex = "0.4.3"
indexmap = "2.0.0"
itertools = "0.11.0"
jj-lib = { version = "=0.8.0", path = "lib", default-features = false }
maplit = "1.0.2"
once_cell = "1.18.0"
pest = "2.7.1"
pest_derive = "2.7.1"
regex = "1.9.1"
rpassword = "7.2.0"
serde = { version = "1.0", features = ["derive"] }
slab = "0.4.8"
tempfile = "3.6.0"
textwrap = "0.16.0"
thiserror = "1.0.43"
timeago = { version = "0.4.1", default-features = false }
toml_edit = { version = "0.19.14", features = ["serde"] }
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["std", "ansi", "env-filter", "fmt"] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.147" }

[dev-dependencies]
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
insta = { version = "1.31.0", features = ["filters"] }
testutils = { path = "lib/testutils" }

[features]
default = []
bench = ["criterion"]
packaging = ["watchman"]
vendored-openssl = ["git2/vendored-openssl", "jj-lib/vendored-openssl"]
watchman = ["jj-lib/watchman"]

[profile.release]
strip = "debuginfo"
codegen-units = 1
