[package]
name = "jujutsu"
version = "0.4.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[[bench]]
name = "diff_bench"
harness = false

[workspace]
members = ["lib"]

[dependencies]
assert_cmd = "2.0.4"
atty = "0.2.14"
chrono = "0.4.19"
clap = { version = "3.1.8", features = ["derive"] }
clap_complete = "3.1.1"
clap_mangen = "0.1"
config = "0.12.0"
criterion = "0.3.5"
dirs = "4.0.0"
git2 = "0.14.2"
hex = "0.4.3"
indoc = "1.0.4"
insta = "1.14.0"
itertools = "0.10.3"
jujutsu-lib = { version = "=0.4.0", path = "lib"}
maplit = "1.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
predicates = "2.1.1"
rand = "0.8.5"
regex = "1.5.5"
tempfile = "3.3.0"
textwrap = "0.15.0"
thiserror = "1.0.30"

[dev-dependencies]
test-case = "2.0.2"
regex = "1.5.5"
criterion = "0.3.5"
criterion_bencher_compat = "0.3.4"
predicates = "2.1.1"

[features]
default = ["vendored-openssl"]
vendored-openssl = ["git2/vendored-openssl", "jujutsu-lib/vendored-openssl"]
