[package]
name = "jujutsu"
version = "0.4.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.60"  # Remember to update CI
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[[bench]]
name = "diff_bench"
harness = false

[workspace]
members = ["lib"]

[dependencies]
atty = "0.2.14"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive"] }
clap_complete = "3.1.4"
clap_mangen = "0.1"
config = { version = "0.13.1", features = ["toml"] }
criterion = "0.3.5"
dirs = "4.0.0"
git2 = "0.14.4"
hex = "0.4.3"
itertools = "0.10.3"
jujutsu-lib = { version = "=0.4.0", path = "lib"}
maplit = "1.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8.5"
regex = "1.5.6"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3.0"
textwrap = "0.15.0"
thiserror = "1.0.31"

[dev-dependencies]
assert_cmd = "2.0.4"
criterion = "0.3.5"
criterion_bencher_compat = "0.3.4"
insta = "1.15.0"
regex = "1.5.6"
predicates = "2.1.1"
test-case = "2.1.0"

[features]
default = ["vendored-openssl"]
vendored-openssl = ["git2/vendored-openssl", "jujutsu-lib/vendored-openssl"]
