// This file is @generated by prost-build.
/// Metadata about the configuration files for jj
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigMetadata {
    /// The absolute path to the workspace's .jj or .jj/repo directory for
    /// workspaces and repos respectively.
    /// Access via file_util::path_to/from_bytes
    #[prost(bytes = "vec", optional, tag = "1")]
    pub path: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// The trust level associated with this repo.
    /// Not used for workspaces.
    #[prost(enumeration = "TrustLevel", tag = "2")]
    pub trust_level: i32,
    /// Contains the most recently approved config.
    #[prost(string, tag = "3")]
    pub managed_config: ::prost::alloc::string::String,
    /// A map from a hex-encoded hash of a config file to true if it is approved,
    /// and false if it is rejected.
    #[prost(map = "string, bool", tag = "4")]
    pub reviewed_configs: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        bool,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrustLevel {
    /// The trust level was never specified.
    /// It will be treated as IGNORED, but the user will be notified and asked
    /// to set the trust level explicitly.
    Unset = 0,
    /// The managed config will be ignored.
    Ignored = 1,
    /// The user will be notified when a new config appears.
    /// They will either approve or reject it.
    Review = 2,
    /// The configuration file is trusted.
    /// Any updates to the managed config will be used automatically.
    Trusted = 3,
}
impl TrustLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "UNSET",
            Self::Ignored => "IGNORED",
            Self::Review => "REVIEW",
            Self::Trusted => "TRUSTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSET" => Some(Self::Unset),
            "IGNORED" => Some(Self::Ignored),
            "REVIEW" => Some(Self::Review),
            "TRUSTED" => Some(Self::Trusted),
            _ => None,
        }
    }
}
