// This file is @generated by prost-build.
/// Metadata about the configuration files for jj
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigMetadata {
    /// The absolute path to the repo or workspace root.
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
