// Copyright 2025 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! A wrapper around retrieval and storage of secure user configuration.

use std::fmt::Debug;
use std::io::Write as _;
use std::path::Path;

use ed25519_dalek::Signer as _;
use ed25519_dalek::SigningKey;
use etcetera::BaseStrategy as _;
use pkcs8::DecodePrivateKey as _;
use pkcs8::EncodePrivateKey as _;
use pkcs8::EncodePublicKey as _;
use prost::Message as _;
use rand::RngCore as _;
use rand::TryRngCore as _;
use rand::rngs::OsRng;
use tempfile::NamedTempFile;
use thiserror::Error;

use crate::file_util::IoResultExt as _;
use crate::file_util::PathError;
use crate::protos::user_config::RepoConfig;
use crate::protos::user_config::SecureUserConfig;
use crate::protos::user_config::WorkspaceConfig;

#[derive(Error, Debug)]
/// Error occurred while dealing with user configs
pub enum UserConfigError {
    /// Failed to determine the home directory
    #[error("Unable to determine the home directory.")]
    HomeDirNotFound,
    /// Failed to read / write to the specified path
    #[error(transparent)]
    PathError(#[from] PathError),
    /// Failed to load the private key.
    #[error(transparent)]
    PrivateKeyError(#[from] ed25519_dalek::pkcs8::Error),
    /// Failed to load the public key.
    #[error(transparent)]
    PublicKeyError(#[from] ed25519_dalek::pkcs8::spki::Error),

    /// Failed to decoode the user configuration file.
    #[error(transparent)]
    DecodeError(#[from] prost::DecodeError),

    /// Missing the user configuration file.
    #[error(
        "This repo was generated by an old version of jj and does not have secure user \
         configuration"
    )]
    LegacyRepo,
}

/// A config file represented by a string instead of backed by a file.
pub trait ConfigType: prost::Message + Default + Clone + Debug {
    /// The name of this type.
    fn kind() -> &'static str;
    /// The string containing the config.
    fn config(&self) -> &str;
}

impl ConfigType for RepoConfig {
    fn kind() -> &'static str {
        "repo"
    }

    fn config(&self) -> &str {
        &self.config
    }
}

impl ConfigType for WorkspaceConfig {
    fn kind() -> &'static str {
        "workspace"
    }

    fn config(&self) -> &str {
        &self.config
    }
}

/// The result of a read of user configuration.
#[derive(Clone, Debug)]
pub enum UserConfig<T: ConfigType> {
    /// We had the correct signature.
    Trusted(T),
    /// Repository has moved from one location to another.
    RepoMoved {
        /// The old path to the repo, encoded as a string.
        from: String,
        /// The new path to the repo, encoded as a string.
        to: String,
        /// The configuration that the repo tried to use.
        config: T,
    },

    /// Repository had the wrong signature.
    InvalidSignature(T),
}

impl<T: ConfigType> UserConfig<T> {
    /// Retrieves the underlying config, regardless of the level of trust.
    pub fn get(&self) -> &T {
        match self {
            Self::Trusted(config)
            | Self::RepoMoved { config, .. }
            | Self::InvalidSignature(config) => config,
        }
    }
}

/// Returns a signing key associated with the current user.
/// Generates a key if we don't yet have one.
fn signing_key() -> Result<SigningKey, UserConfigError> {
    let strategy = match etcetera::choose_base_strategy() {
        Ok(s) => s,
        Err(_) => return Err(UserConfigError::HomeDirNotFound),
    };
    let key_dir = strategy.data_dir().join("jj/keys");
    let signing_key = key_dir.join("ed25519.der");
    let verifying_key = key_dir.join("ed25519.der.pub");
    Ok(match std::fs::read(&signing_key).context(&signing_key) {
        Ok(bytes) => SigningKey::from_pkcs8_der(&bytes)?,
        Err(e) if e.source.kind() == std::io::ErrorKind::NotFound => {
            std::fs::create_dir_all(&key_dir).context(&key_dir)?;

            let mut csprng = OsRng.unwrap_err();
            let key = SigningKey::generate(&mut csprng);
            // We never actually use the public key.
            // But write it to disk so we don't lose it in case we decide to use it in the
            // future.
            key.verifying_key()
                .write_public_key_der_file(&verifying_key)?;
            key.write_pkcs8_der_file(&signing_key)?;
            key
        }
        Err(e) => return Err(UserConfigError::from(e)),
    })
}

/// Reads the user configuration from a repository for the current user.
pub fn read_user_config<T: ConfigType>(d: &Path) -> Result<UserConfig<T>, UserConfigError> {
    let path = d.join("config");
    let buf = match std::fs::read(&path).context(&path) {
        Ok(buf) => buf,
        Err(e) if e.source.kind() == std::io::ErrorKind::NotFound => {
            // Eg. .jj/workspace => check that .jj exists to check if the repo itself
            // exists.
            if d.parent().unwrap().exists() {
                return Err(UserConfigError::LegacyRepo);
            } else {
                // This repo doesn't exist. So we create some new empty config.
                return Ok(UserConfig::Trusted(Default::default()));
            }
        }
        Err(e) => return Err(UserConfigError::PathError(e)),
    };
    let secure_config = SecureUserConfig::decode(&*buf)?;
    let config = T::decode(&*secure_config.storage)?;
    let key = signing_key()?;

    let sign = |s: &str| {
        let mut to_sign = secure_config.storage.clone();
        to_sign.extend(&secure_config.salt);
        to_sign.extend(s.as_bytes());
        key.sign(&to_sign).to_bytes()
    };

    let canonical = dunce::canonicalize(d)
        .context(d)
        .map_err(UserConfigError::PathError)?
        .to_string_lossy()
        .to_string();
    if sign(&canonical) == *secure_config.signature {
        Ok(UserConfig::Trusted(config))
    } else if config.config().is_empty() {
        // We don't trust the providence of the configuration, but it's empty so we'll
        // just replace it with a similarly empty one.
        Ok(UserConfig::Trusted(Default::default()))
    } else if sign(&secure_config.path) == *secure_config.signature {
        Ok(UserConfig::RepoMoved {
            from: secure_config.path,
            to: canonical,
            config,
        })
    } else {
        Ok(UserConfig::InvalidSignature(config))
    }
}

/// Writes a given configuration for a repository.
pub fn write_user_config<T: prost::Message>(d: &Path, config: &T) -> Result<(), UserConfigError> {
    let content = config.encode_to_vec();
    let mut salt = [0u8; 8];
    rand::rng().fill_bytes(&mut salt);
    std::fs::create_dir_all(d).context(d)?;
    let canonical = dunce::canonicalize(d)
        .context(d)?
        .to_string_lossy()
        .to_string();

    let key = signing_key()?;
    let mut to_sign = content.clone();
    to_sign.extend(salt);
    to_sign.extend(canonical.as_bytes());
    let signature = key.sign(&to_sign);

    let secure_config = SecureUserConfig {
        storage: content,
        salt: salt.to_vec(),
        path: canonical,
        signature: signature.to_vec(),
    };

    // Atomically write to the file.
    let mut f = NamedTempFile::new_in(d).context(d)?;
    f.write_all(&secure_config.encode_to_vec()).context(d)?;
    let out = d.join("config");
    std::fs::rename(f.path(), &out).context(&out)?;

    Ok(())
}
