[aliases]
# Placeholder: added by user

[format]
tree-level-conflicts = true

[ui]
paginate = "auto"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
log-word-wrap = false
log-synthetic-elided-nodes = false

[snapshot]
max-new-file-size = "1MiB"
