[colors]
"error" = "red"
"warning" = "yellow"
"hint" = "blue"

"conflict_description" = "yellow"
"conflict_description difficult" = "red"

"commit_id" = "blue"
"change_id" = "magenta"
"author" = "yellow"
"author timestamp" = "cyan"
"committer" = "yellow"
"committer timestamp" = "cyan"
"working_copies" = "magenta"
"branch" = "magenta"
"branches" = "magenta"
"tags" = "magenta"
"git_refs" = "magenta"
"git_head" = "magenta"
"divergent" = "red"
"conflict" = "red"

# TODO: This near-duplication of the lines above is unfortunate. Should we
# allow adding and clearing the "bright" bit somehow? Or should we instead
# use a different background color? (We don't have support for background
# colors yet.)

"working_copy commit_id" = "bright blue"
"working_copy change_id" = "bright magenta"
"working_copy author" = "bright yellow"
"working_copy author timestamp" = "bright cyan"
"working_copy committer" = "bright yellow"
"working_copy committer timestamp" = "bright cyan"
"working_copy working_copies" = "bright magenta"
"working_copy branch"  = "bright magenta"
"working_copy branches" = "bright magenta"
"working_copy tags" = "bright magenta"
"working_copy git_refs" = "bright magenta"
"working_copy divergent" =  "bright red"
"working_copy conflict" = "bright red"
"working_copy description" = "bright white"
"diff header" = "yellow"
"diff file_header" = "bright white"
"diff hunk_header" = "cyan"
"diff removed" = "red"
"diff added" = "green"
"diff modified" = "cyan"
"op-log id" = "blue"
"op-log user" = "yellow"
"op-log time" = "cyan"
"op-log tags" = "white"
"op-log head id" = "bright blue"
"op-log head user" = "bright yellow"
"op-log head time" = "bright cyan"
"op-log head description" = "bright white"
"op-log head tags" = "bright white"
