[colors]
"error" = "red"
"warning" = "yellow"
"hint" = "cyan"

"conflict_description" = "yellow"
"conflict_description difficult" = "red"

"commit_id" = "blue"
"change_id" = "magenta"

# Unique prefixes and the rest for change & commit ids
"prefix" = { bold = true}
"rest" = "bright black"
"divergent rest" = "red"
"divergent prefix" = {fg = "red", underline=true}

"email" = "yellow"
"timestamp" = "cyan"
"working_copies" = "magenta"
"branch" = "magenta"
"branches" = "magenta"
"tags" = "magenta"
"git_refs" = "magenta"
"git_head" = "magenta"
"divergent" = "red"
"divergent change_id"="red"
"conflict" = "red"
"empty" = "green"

"working_copy" = { bold = true }
"working_copy commit_id" = "bright blue"
"working_copy change_id" = "bright magenta"
# We do not use bright yellow because of how it looks on xterm's default theme.
# https://github.com/martinvonz/jj/issues/528
"working_copy email" = "yellow"
"working_copy timestamp" = "bright cyan"
"working_copy working_copies" = "bright magenta"
"working_copy branch"  = "bright magenta"
"working_copy branches" = "bright magenta"
"working_copy tags" = "bright magenta"
"working_copy git_refs" = "bright magenta"
"working_copy divergent" =  "bright red"
"working_copy divergent change_id"="bright red"
"working_copy conflict" = "bright red"
"working_copy empty" = "bright green"
"diff header" = "yellow"
"diff file_header" = { bold = true }
"diff hunk_header" = "cyan"
"diff removed" = "red"
"diff added" = "green"
"diff modified" = "cyan"
"op-log id" = "blue"
"op-log user" = "yellow"
"op-log time" = "cyan"
"op-log head" = { bold = true }
"op-log head id" = "bright blue"
"op-log head user" = "yellow"  # No bright yellow, see comment above
"op-log head time" = "bright cyan"
