[aliases]
# Placeholder: added by user

[git]
push = "origin"
fetch = "origin"

[revset-aliases]
# Placeholder: added by user

[ui]
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
log-word-wrap = false
