[templates]
commit_summary = '''
format_short_id(commit_id) " "
if(description, description.first_line(), description_placeholder)
'''

log = '''
label(if(current_working_copy, "working_copy"),
  separate(" ",
    if(divergent,
      label("divergent", format_short_id(change_id) "??"),
      format_short_id(change_id)),
    format_short_signature(author),
    format_timestamp(committer.timestamp()),
    branches,
    tags,
    working_copies,
    git_head,
    format_short_id(commit_id),
    if(conflict, label("conflict", "conflict")),
  )
  "\n"
  if(empty, label("empty", "(empty)") " ")
  if(description, description.first_line(), description_placeholder)
  "\n"
)
'''

# Defined as alias to allow 'log -T show'
show = 'show'

[template-aliases]
'description_placeholder' = 'label("description", "(no description set)")'

# TODO: Add branches, tags, etc
# TODO: Indent the description like Git does
'show' = '''
"Commit ID: " commit_id "\n"
"Change ID: " change_id "\n"
"Author: " author " (" format_timestamp(author.timestamp()) ")\n"
"Committer: " committer " (" format_timestamp(committer.timestamp()) ")\n"
"\n"
if(description, description, description_placeholder "\n")
"\n"
'''
