[alias]
# Measure code coverage with cargo-llvm-cov and nextest. Requires a nightly
# toolchain.
#
# The default test-exclusion heuristics aren't quite enough for us, so we get
# rid of a few extra things below.
cov = [
    "llvm-cov",
    "--branch",
    "nextest",
    "--exclude-from-report",
    "testutils",
    "--exclude-from-report",
    "gen-protos",
    "--ignore-filename-regex",
    "(cli/testing/|lib/src/(secret_backend|test_signing_backend)\\.rs|cli/build\\.rs)",
]

[target.'cfg(all(target_family = "windows", target_env = "msvc"))']
linker = "rust-lld.exe"
rustflags = [
    # NOTE: on Windows, build with the static CRT, so that produced .exe files don't
    # depend on vcruntime140.dll; otherwise the user requires visual studio if they
    # download a raw .exe e.g. from the CI system
    "-Ctarget-feature=+crt-static",

    # Without this, at opt-level = 0 (dev profile) the compiler will generate code
    # with enough async futures that the default 1MiB stack will overflow.
    "-Clink-arg=/STACK:8388608" # 8MiB
]
