[package]
name = "jj-lib-proc-macros"
description = "Proc macros for the jj-lib crate (deprecated use jj-core-proc-macros instead)"

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }

include = ["/LICENSE", "/src/"]

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true
