[profile.dev]
debug = "none"
incremental = false

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
# NOTE: on Windows, build with the static CRT, so that produced .exe files don't
# depend on vcruntime140.dll; otherwise the user requires visual studio if they
# download a raw .exe
rustflags = ["-Ctarget-feature=+crt-static"]
