# Basic template of config settings

# Don't forget to change these to your own details!
user.name = "YOUR NAME" 
user.email = "YOUR_EMAIL@example.com"

ui.color = "auto" # the default
# ui.color = never # no color

ui.relative-timestamps = false # the default
# ui.relative-timestamps = true # renders timestamps relatively, e.g. "x hours ago"

ui.editor = "pico" # the default
# ui.editor = "vim"

ui.diff-editor = "meld" # default, requires meld to be installed
# ui.diff-editor = "vimdiff"

ui.merge-editor = "meld" # default
# ui.merge-editor = "vimdiff"
# ui.merge-editor = "kdiff3"

# The three merge tools above are pre-configured. For detailed information
# about how to change the default configuration or how to configure another tool,
# see documentation in config.md. An example:

# merge-tools.meld.program = "C:\\Program Files\\Meld\\meld.exe" # If not in PATH
