# Basic template of config settings

# Don't forget to change these to your own details!
user.name = "YOUR NAME" 
user.email = "YOUR_EMAIL@example.com"

ui.color = "auto" # the default
# ui.color = never # no color

ui.editor = "pico" # the default on Unix
# ui.editor = "vim"

ui.diff-editor = "meld" # default, requires meld to be installed
# ui.diff-editor = "vimdiff"

ui.merge-editor = "meld" # default
# ui.merge-editor = "vimdiff"
# ui.merge-editor = "kdiff3"

# Relative timestamp rendered as "x days/hours/seconds ago"
template-aliases.'format_timestamp(timestamp)' = 'timestamp.ago()'

# The three merge tools above are pre-configured. For detailed information
# about how to change the default configuration or how to configure another tool,
# see documentation in config.md. An example:

# merge-tools.meld.program = "C:\\Program Files\\Meld\\meld.exe" # If not in PATH
