// Copyright 2020 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Example:
// "commit: " ++ short(commit_id) ++ "\n"
// predecessors.map(|p| "predecessor: " ++ p.commit_id)
// parents.map(|p| p.commit_id ++ " is a parent of " ++ commit_id)

// If making significant changes to this grammar, consider also updating the
// tree-sitter grammar: https://github.com/bryceberger/tree-sitter-jjtemplate

WHITESPACE = _{ " " | "\t" | "\r" | "\n" | "\x0c" }

string_escape = @{
  "\\"
  ~ ("t" | "r" | "n" | "0" | "e" | ("x" ~ ASCII_HEX_DIGIT{2}) | "\"" | "\\")
}
string_content_char = @{ !("\"" | "\\") ~ ANY }
string_content = @{ string_content_char+ }
string_literal = ${ "\"" ~ (string_content | string_escape)* ~ "\"" }

raw_string_content = @{ (!"'" ~ ANY)* }
raw_string_literal = ${ "'" ~ raw_string_content ~ "'" }

integer_literal = @{
  ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*
  | "0"
}

identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

concat_op = { "++" }
logical_or_op = { "||" }
logical_and_op = { "&&" }
eq_op = { "==" }
ne_op = { "!=" }
ge_op = { ">=" }
gt_op = { ">" }
le_op = { "<=" }
lt_op = { "<" }
add_op = { "+" }
sub_op = { "-" }
mul_op = { "*" }
div_op = { "/" }
rem_op = { "%" }
logical_not_op = { "!" }
negate_op = { "-" }
pattern_kind_op = { ":" }
prefix_ops = _{ logical_not_op | negate_op }
infix_ops = _{
  logical_or_op
  | logical_and_op
  | eq_op
  | ne_op
  | ge_op
  | gt_op
  | le_op
  | lt_op
  | add_op
  | sub_op
  | mul_op
  | div_op
  | rem_op
}

function = { identifier ~ "(" ~ function_arguments ~ ")" }
keyword_argument = { identifier ~ "=" ~ template }
argument = _{ keyword_argument | template }
function_arguments = {
  argument ~ ("," ~ argument)* ~ ","?
  | ""
}
lambda = {
  "|" ~ formal_parameters ~ "|" ~ template
}
formal_parameters = {
  identifier ~ ("," ~ identifier)* ~ ","?
  | ""
}

// Negating inside of these rules will produce a Pair on each success that needs
// to be filtered out before Pratt parsing. However, it also results in a nicely
// named error, because it fails on a specific rule, which affords better UX.
//
// Currently, each of these is set to limit of 64, with the exception of the
// `recursive_depth_limit_reached` which is will be anywhere between 64 and
// 128 repetitions (due to shared stacked between all rules).
//
// TODO: move this into an inline grammar into the template_parser.rs -- so that
// bounds can be set as consts and kepty in sync for tests.
prefix_op_width_limit_reached = {
  !PEEK[65..]
}

infix_op_width_limit_reached = {
  !PEEK[65..]
}

method_chain_width_limit_reached = {
  !PEEK[65..]
}

// All of the Pratt recursion happens through "primary", so it is bound recursively to
// a maximum nesting depth P. However, due to bounding the expression_range as well,
// and stack sharing, the limit brought in by that bound E can also count, where in
// worst case scenario only (P - E) nesting depth is allowed.
recursive_depth_limit_reached = {
  !PEEK[129..]
}

// NOTE: Pattern identifiers additionally allow "-" in them, which results in
// some oddness with the `-` operator.
pattern_identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_" | "-")* }
pattern = ${ pattern_identifier ~ pattern_kind_op ~ pattern_value_expression }

// Instead of putting a bound inside primary, template and pattern_value_expression
// are bound instead. These two rules form a feedback vertex set for the recursive
// cycle through the primary. This is done for better error reporting (otherwise the
// recursive_depth_limit_reached is not reported by pest).
//
// When pattern_value_expression is matched, an empty string is pushed to the stack.
// Empty string always matches, and doesn't consume any tokens. Next, a bound
// checking rule is used, which, for a given bound B, peeks at the stack offsetted
// by B+1. If that many empty strings have already been pushed, the rule must
// have already recursed for B levels, an empty string pattern is tried, which
// always succeeds, and the rule fails. If the recursing sub-rule doesn't recurse,
// DROP is called, which just drops the top of the stack, without trying to match.
// If less than B strings have been pushed to the stack, PEEK will fail and the
// bound-checking rule succeeds, allowing recursion to potentially continue.
pattern_value_expression = {
  PUSH("") ~ recursive_depth_limit_reached
  ~ prefixed_term
  ~ DROP
}

primary = {
  ("(" ~ template ~ ")")
  | function
  | lambda
  | pattern
  | identifier
  | string_literal
  | raw_string_literal
  | integer_literal
}

// Recursively bound the number of chained method repetitions to the bound set
// in method_chain_width_limit_reached. See comment above pattern_value_expression
// for explanation of the mechanism. In addition, adding a fallback rule that
// matches empty string (always succeeds) provides a base case for the recursion
// and also encodes the case where there are *no* chained methods. This is basically
// an alternative to writing ("." ~ function){,B}. The latter is simpler and has
// its merits, but using it will significantly increase the binary size. Note also
// that it can also be used for limiting the token tree "width", but not its nesting depth.
bounded_method_chain = _{
  "." ~ function
  ~ PUSH("") ~ method_chain_width_limit_reached
  ~ bounded_method_chain
  ~ DROP
  | ""
}

term = {
  primary ~ bounded_method_chain
}

// See comment above bounded_method_chain.
bounded_prefix_ops = _{
  prefix_ops
  ~ PUSH("") ~ prefix_op_width_limit_reached
  ~ bounded_prefix_ops
  ~ DROP
  | ""
}

prefixed_term = _{
  bounded_prefix_ops ~ term
}

// See comment above bounded_method_chain.
bounded_infix_terms = _{
  infix_ops ~ prefixed_term
  ~ PUSH("") ~ infix_op_width_limit_reached
  ~ bounded_infix_terms
  ~ DROP
  | ""
}

expression = {
  prefixed_term ~ bounded_infix_terms
}

// Whitespace is allowed in value part of <name>:(<template>) expression.
//
// While the rule is recursively bound to limit the possible tree depth,
// we still allow a unbounded sequence of concatenated expressions,
// because these are parsed into a single vector. So while, they could
// potentially grow the vector indefinitely, they cannot cause a stack
// overflow.
template = !{
  PUSH("") ~ recursive_depth_limit_reached
  ~ expression ~ (concat_op ~ expression)*
  ~ DROP
}

program = _{ SOI ~ template? ~ EOI }

function_alias_declaration = {
  identifier ~ "(" ~ formal_parameters ~ ")"
}
pattern_alias_declaration = {
  pattern_identifier ~ pattern_kind_op ~ identifier
}
alias_declaration = _{
  SOI ~ (function_alias_declaration
        | pattern_alias_declaration
        | identifier) ~ EOI
}
