name: ci

on:
  pull_request:
  merge_group:

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number
      || github.event.merge_group.head_ref
    }}
  cancel-in-progress: true

permissions: {}

jobs:

  mise-codespell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run check:codespell
  mise-codespell-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run check:codespell
