name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
        with:
          check_filenames: true
          check_hidden: true
          skip: ./target,./.jj,*.lock
          ignore_words_list: crate
