name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630
        with:
          check_filenames: true
          check_hidden: true
          skip: ./target,./.jj,*.lock
          # `Wirth` is the proper name of one of our contributors in the changelog.
          # It seems Codespell does not allow per-file ignore_word_list.
          ignore_words_list: crate,NotIn,Wirth
