name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: codespell-project/actions-codespell@22ff5a2e4b591290baf82d47c9feadac31c65441
        with:
          check_filenames: true
          check_hidden: true
          skip: target,.jj
          ignore_words_list: crate,nd,nD
