name: Automatically merge Dependabot PRs

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot-auto-merge:
    name: 'Dependabot auto-merge'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    if: >-
      ${{
        github.event.review.state == 'approved'
        && github.event.pull_request.user.name == 'dependabot[bot]'
      }}
    steps:
    - name: Automatically merge Dependabot PRs
      run: gh pr merge --rebase "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
