name: website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prerelease-docs-build-deploy:
    if: github.repository_owner == 'martinvonz' # Stops this job from running on forks
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run:  "git fetch origin gh-pages --depth=1"
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
      - name: Install poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd
        with:
          poetry-version: latest
      - name: Install dependencies, compile and deploy docs
        run: |
          git config user.name 'jj-docs[bot]'
          git config user.email 'jj-docs[bot]@users.noreply.github.io'
          .github/scripts/docs-build-deploy 'https://martinvonz.github.io/jj' prerelease --push
      - name: "Show `git diff --stat`"
        run: git diff --stat gh-pages^ gh-pages || echo "(No diffs)"
