name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@4b933aa7ebcc94a6174cf1364864e957b4910265
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --print-build-logs --show-trace
