name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --print-build-logs --show-trace
