name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        mode: [ "flake check", "build" ]
    runs-on: ${{ matrix.os }}
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@65d7c888b2778e8cf30a07a88422ccb23499bfb8
      - uses: DeterminateSystems/magic-nix-cache-action@a04e6275a6bea232cd04fc6f3cbf20d4cb02a3e1
      - run: nix ${{ matrix.mode }} --print-build-logs --show-trace
