name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@5620eb4af6b562c53e4d4628c0b6e4f9d9ae8612
      - uses: DeterminateSystems/magic-nix-cache-action@a04e6275a6bea232cd04fc6f3cbf20d4cb02a3e1
      - run: nix build --print-build-logs --show-trace
