name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --print-build-logs --show-trace
