name: pr

on:
  pull_request:

permissions: {}

jobs:
  # The actual `required-checks` job is defined in `ci.yml` and only
  # runs for `merge_group` events. This hack ensures that it doesn’t
  # block the merge for pull requests.
  required-checks:
    name: required checks (merge queue)
    if: false
    runs-on: ubuntu-latest
    # Should never be run
    steps:
    - run: exit 1
